### ISSUE TITLE
Is there a way to save training for later use?

### ISSUE THREAD

**Issue by occultknowledge** [lorenanda/POEtry-generation#1]
Hey great job! I am using my own training poetry source. Is there a way to save the training so I can simply go back after that at a later time and use it to make more poetry. Please forgive me if there is already, but I did not see any weights or vocab files. Thanks in advance.

**Comment by lciutacu** [comment]
Hi @occultknowledge, I'm glad to hear you're using this! 
You can save the trained model with `model.save("my_model.h5")` and when you want to use it again, just load it with `load_model("my_model.h5")`.
