### ISSUE TITLE
Training large amounts of text crashes the runtime.

### ISSUE THREAD

**Issue by occultknowledge** [lorenanda/POEtry-generation#2]
Hi again. I am curious if there are some settings I can tweak to train larger training texts around (5-10 megs) Currently it crashes the runtime on colab? Thanks in advance.

**Comment by lciutacu** [comment]
I'm not sure about that. The text size doesn't seem that large and from my experience Colab can handle that. You could try adding a smaller `batch_size` in the `Embedding` layer.
